name: Build Level Readiness

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-windows:
    name: Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          target: Win64
          build-config: RelWithDebInfo

      - name: Upload .geode artifact
        uses: actions/upload-artifact@v4
        with:
          name: Level-Readiness-Windows
          path: ${{ steps.build.outputs.build-output }}
          if-no-files-found: error
